### ISSUE TITLE
Overlap in debug mode

### ISSUE THREAD

**Issue by Tastaturberuf** [may17/contao-m17StickyBEFooter#21]
Contao 3.3.5

The debug bar overlaps the button bar.

**Comment by harry-boldt** [comment]
Man kann sich damit behelfen, indem man in der Datei "system/modules/m17StickyBEFooter/assets/m17StickyBeFooter.css "die folgende Deklaration korrigiert:

.stickySave .tl_submit_container {
   bottom: 36px;
}

Das ist natürlich hartkodiert (hält nur bis zum nächsten Update) und prüft auch nicht, ob der Debug-Modus überhaupt eingeschaltet ist, aber es funktioniert wenigstens.

**Comment by Tastaturberuf** [comment]
:+1:

**Comment by may17** [comment]
Danke für das Feedback Harry. Ich werde demnächst eine neue Version veröffentlichen.

**Comment by Tastaturberuf** [comment]
:+1::+1:

**Comment by may17** [comment]
Hm ich hab das gerade in Contao 3.4 getestet und kann den fehler nicht reproduzieren. Gibt es den fehler nur bei Contao 3.3 ?

**Comment by Tastaturberuf** [comment]
Besteht in allen (zumindest 3er) Versionen.

**Comment by may17** [comment]
Ist behoben bzw. war im master branch schon längst behoben, daher hatte ich den Fehler nicht. Neue Version ist im ER und sollte via composer bereit stehen.

Danke für euer Feedback.

**Comment by Tastaturberuf** [comment]
Danke für den Fix. Klappt super.
