### ISSUE TITLE
Sprachdatei fehlt => Beschreibung in Einstellungen/inaktive Erweiterungen fehlt

### ISSUE THREAD

**Issue by mathContao** [may17/contao-m17StickyBEFooter#22]
In den Einstellungen im Abschnitt "inaktive Erweiterungen" werde im Normalfall die Erweiterungen mit dem Erweiterungsnamen + sprachspezifische Beschreibung angezeigt.

Bei dieser Erweiterung leider nicht:
![einstellungen-screenshot](https://cloud.githubusercontent.com/assets/1645099/8895572/4b0ba014-33df-11e5-8212-a80437616234.JPG)

Contao 3.4.5 mit m17-sticky-backend-footer V2.0.5, Build7 (=aktuellste Version)

Die Beschreibung fehlt, weil die Sprachdateien fehlen.

Ordner: languages/de/modules.php

dort müsste rein:
```
$GLOBALS['TL_LANG']['MOD']['m17StickyBEFooter
'] = array('Sticky Footer im Backend', 'Sticky Footer für den Speichern-Bereich im Backend');
```

**Comment by may17** [comment]
Fixed in release 2.0.6
