### ISSUE TITLE
Fehler im contao package

### ISSUE THREAD

**Issue by agoat** [may17/contao-m17StickyBEFooter#23]
Hallo,
Bei der Installation über das Contao Extension Repository werden nur zwei php Dateien für die Sprache installiert aber keine assets usw. Natürlich hat Erweiterung dadurch keinerlei funktion. 
Beim Release von github sind logischerweise alle Dateien drin. Da ist vermutlich ein Syncronisations-Fehler passiert.

Arne

**Comment by may17** [comment]
Narf... Danke für den Hinweis. Sollte korrigiert sein, da ist in der Tat was beim übertragen des tags schief gelaufen.
