### ISSUE TITLE
Contao 4 Managed Edition - Installation

### ISSUE THREAD

**Issue by daniel-nemeth** [may17/contao-m17StickyBEFooter#25]
Hi,
I tried to install your extension to a Contao 4 Managed Edition.

There I get an error:
![screen shot 2017-05-22 at 07 28 22](https://cloud.githubusercontent.com/assets/5083254/26293910/68d75a1e-3ec0-11e7-8602-54ab1ac07aee.png)

Thanks.

**Comment by Defcon0** [comment]
Same here in standard edition.

**Comment by may17** [comment]
I ve merged davids pull request. Please Check if it Works now for you.

**Comment by jankout** [comment]
Unfortunately, It does not work with the latest 4.3.x version. I have the same error message.

**Comment by may17** [comment]
There was an error on packagist with the Composer.json so the new release isn't availible there. I will check this later.

**Comment by may17** [comment]
I hope you reconized my bugfix!? Is that issue resolved for you guys?
