### ISSUE TITLE
Sticky footer hides last legend of notification center attachements legend

### ISSUE THREAD

**Issue by cliffparnitzky** [may17/contao-m17StickyBEFooter#30]
The sticky footer hides the legend "Attachements" in `notification_center` popup for editing the language:

![image](https://user-images.githubusercontent.com/1247552/69330296-f675fa80-0c52-11ea-86a1-c816043b78f8.png)

The popup is an iframe with `body` class `popup`.

Solution:
a. adding a selector `body.popup.stickySave .tl_submit_container` for overwriting the CSS definitions
b. using JS for deactivating the CSS
c. ???

@may17 What will be your preferred solution? I can provide a PR.

**Comment by may17** [comment]
Thk you @cliffparnitzky wich version did you use? The stable or the "new" beta version?

You can fix that issue if you like :)

**Comment by may17** [comment]
Oh hold i prefer solution a

**Comment by cliffparnitzky** [comment]
> Thk you @cliffparnitzky wich version did you use? The stable or the "new" beta version?

That's it.

I tried the beta version and everything works fine. There is something special when the vertical scrolling is near the end ... that solves the probleme.

In my opinion we can close the ticket and use the beta.

**Comment by Kahmoon** [comment]
How can i use the beta Version via Contao Manager? ^3.0 does not work
