### ISSUE TITLE
Sticky Header?

### ISSUE THREAD

**Issue by JensB74** [may17/contao-m17StickyBEFooter#31]
It would be very nice, if the header could be sticky too, or only one row, that one with the "edit multiple" (?).

Und noch auf deutsch, es wäre klasse, wenn zumindest der Link "Mehrere bearbeiten" auch Sticky werden könnte, evtl. macht es sogar Sinn noch mehr Inhalte aus dem Kopfbereich Sticky zu machen.
Oft bin ich unten irgendwo auf der Seite und denke, ah, hier muss ich noch an mehreren Seiten etwas ändern und muss dann erst wieder hochscrollen, klicken und wieder nach unten suchen ..

Erste Sahne wäre, wenn es per Ajax ginge und man nach dem Klick an der selben Stelle bliebe, wo man auf "Mehrere bearbeiten" geklickt hat, ob das möglich ist wage ich aber gerade zu bezweifeln ..

Beste Grüße

**Comment by may17** [comment]
Sounds interesting but that feature is out off scope for this exension. It should be a new seperate extension. If you need an extension like that quickly, you should contact me via https://jgreg.dev to get an offer.
